### ISSUE TITLE
Need to be able to assign custom Gecko

### ISSUE THREAD

**Issue by shinglyu** [Mozilla-TWQA/MozITP#16]

**Comment by shinglyu** [comment]
Quote 陳博: "剛剛提到送 try 的資訊在這:
https://wiki.mozilla.org/ReleaseEngineering/TryServer#Using_a_custom_Gaia

用 gecko 的 push-to-try 把 custom gecko patch 推上去，然後指向自己在 github 的 custom gaia 這樣"

**Comment by chenpighead** [comment]
FYI this script that I used before.
https://gist.github.com/chenpighead/5d234f1a82427a000adc
