### ISSUE TITLE
All Tests on Jenkins are always passing

### ISSUE THREAD

**Issue by shinglyu** [Mozilla-TWQA/MozITP#53]
Run tests in `./test/`, they are always marked as SUCCESSFUL on jenkins, even if there are errors.

**Comment by shinglyu** [comment]
Use `source launch.sh` solves part of the problem, but the GIP test error is not captured yet.

**Comment by askeing** [comment]
Maybe we can add a new job which run `exit 1` for manually testing the Jenkins :P

**Comment by askeing** [comment]
need verify
