### ISSUE TITLE
Write a flashtool test script

### ISSUE THREAD

**Issue by shinglyu** [Mozilla-TWQA/MozITP#54]
Check if 
No device connected => "ERROR: Can not find device, please connect your device." in stdout
Has device connected => The following result:

```
Askeings-MacBook-Pro:MozITP Askeing$ yes q | vagrant ssh -c b2g_quick_flash
INFO: Device found: flame

What would you like to do?
    0) mozilla-central
    1) mozilla-b2g44_v2_5
    q) Exit
Please select [ENTER]:Askeings-MacBook-Pro:MozITP Askeing$
```

**Comment by askeing** [comment]
Fixed by https://github.com/Mozilla-TWQA/MozITP/commit/11d87dec502a4adfa100f310442bf51e3a572677
