### ISSUE TITLE
Update to Node v4.0

### ISSUE THREAD

**Issue by shinglyu** [Mozilla-TWQA/MozITP#7]
Currently the GIJ fails because it needs node 4.0. Need to update and test it.

**Comment by mwargers** [comment]
Cool, thanks for fixing this.

**Comment by mwargers** [comment]
Hi Shing, I tried to change this to get it working:
--- a/scripts/gij.sh
+++ b/scripts/gij.sh
@@ -11,8 +11,8 @@ sudo apt-get update
 sudo apt-get install -y build-essential libssl-dev pcregrep
 curl -o- https://raw.githubusercontent.com/creationix/nvm/$NVM_VER/install.sh | bash #Notice the version may change
 source ~/.nvm/nvm.sh
-nvm install 0.12
-nvm use 0.12
+nvm install 4.2
+nvm use 4.2

But I still get the error message:
Please use v4.2 of nodejs or it may cause unexpected error.
Minimum required version of nodejs v4 not satisfied. Aborting. Install the required minimum version before continuing.

Do you know what needs to be changed?

**Comment by shinglyu** [comment]
Oh my. I think we might have to talk to Aus, otherwise we might need to fix the gaia version.

**Comment by shinglyu** [comment]
cc @askeing

**Comment by shinglyu** [comment]
I tried to upgrade to node 4.2, the error message goes away, but the `make test-integration` command fails because of the `sockit-to-me` package. I'm looking into it.

**Comment by mwargers** [comment]
@shinglyu How did you upgrade to 4.2? What do I need to do to be able to do that?

**Comment by shinglyu** [comment]
@mwargers Just change the nvm commad like this: https://github.com/Mozilla-TWQA/MozITP/commit/f311626d199aca915555cff66db83fd54bd4c42a#diff-248114233d816323c4805083571f930fR15

**Comment by shinglyu** [comment]
It turns out that we need to install `clang`, closed by https://github.com/Mozilla-TWQA/MozITP/commit/bc231c706cda3dbd8b8a413f04f51985b612d2e4
