### ISSUE TITLE
mozilla-download: No such file or directory when trying to run "./launch.sh gij"

### ISSUE THREAD

**Issue by mwargers** [Mozilla-TWQA/MozITP#8]
After this issue was fixed: https://github.com/Mozilla-TWQA/MozITP/issues/7
I now get this error when trying to run "./launch.sh gij":

2015-12-21 18:00:07: basic_code_modules.cc:88: INFO: No module at 0x2b22ea9dca90
2015-12-21 18:00:07: basic_code_modules.cc:88: INFO: No module at 0x2b22e81c6f60
require.js optimize ok
[OK] rjs optimize
[app] building music-oga app...
r.js optimize ok
[preprocessor] FIREFOX_SYNC true /home/vagrant/gaia/build_stage/settings,elements,root.html
[preprocessor] FIREFOX_SYNC true /home/vagrant/gaia/build_stage/settings,index.html
Finished: test ui config file: ./dev_apps/test-agent/config.json
Finished: Generating extensions
Profile Ready: please run [b2g|firefox] -profile /home/vagrant/gaia/profile-test
DEBUG=\* ./node_modules/.bin/mozilla-download \
    --product mulet \
    --branch mozilla-central \
    /home/vagrant/gaia
/bin/bash: ./node_modules/.bin/mozilla-download: No such file or directory
make: **\* [mulet] Error 127
Connection to 127.0.0.1 closed.
mwargers:MozITP mwargers$ 

Perhaps this is a credentials issue or something?

**Comment by shinglyu** [comment]
Sorry for the late response.

That was probably due to some mis-configuration of nvm. I fixed it and gij is running on my Jenkins smoothly. 

Please do let me know if you still have the same problem.

**Comment by mwargers** [comment]
I still have the same problem.

**Comment by shinglyu** [comment]
Oh, I found that if you failed once due to the previous bug, you'll always get the error message in the following runs. The solution is to go into the interactive shell, delete the `node_modules` folder in `gaia` and run gij again.

```
./launch.sh 
# Wait for the interactive menu
# Choose option "Interactive shell"
cd ~/gaia
rm -rf node_modules
exit
# Will go back to the interactive menu
# Select the Run GIJ on Mulet option
```

**Comment by mwargers** [comment]
I'm not getting this error anymore, but now I get this error:
/home/vagrant/gaia/tv_apps/dashboard/test/marionette/dashboard_test.js
/home/vagrant/gaia/tv_apps/dashboard/test/marionette/digital_clock_test.js
/home/vagrant/gaia/tv_apps/smart-home/test/marionette/smart_home_test.js
/home/vagrant/gaia/tv_apps/smart-system/fxa/test/marionette/fxa_launch_test.js
/home/vagrant/gaia/tv_apps/smart-system/fxa/test/marionette/fxa_screen_flow_test.js
/home/vagrant/gaia/tv_apps/smart-system/test/marionette/app_install_dialog_test.js
/home/vagrant/gaia/tv_apps/smart-system/test/marionette/app_modal_dialog_test.js

---

/home/vagrant/gaia/node_modules/.bin/gaia-marionette: line 169: echo: write error: Resource temporarily unavailable

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.2.2/bin/node" "/home/vagrant/.nvm/versions/node/v4.2.2/bin/npm" "run" "marionette" "--" "--buildapp=desktop" "--reporter=spec" "--marionette-capabilities=/home/vagrant/gaia/tests/jsmarionette/capabilities.json"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! gaia@0.0.3 marionette: `gaia-marionette "--buildapp=desktop" "--reporter=spec" "--marionette-capabilities=/home/vagrant/gaia/tests/jsmarionette/capabilities.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gaia@0.0.3 marionette script 'gaia-marionette "--buildapp=desktop" "--reporter=spec" "--marionette-capabilities=/home/vagrant/gaia/tests/jsmarionette/capabilities.json"'.
npm ERR! This is most likely a problem with the gaia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gaia-marionette "--buildapp=desktop" "--reporter=spec" "--marionette-capabilities=/home/vagrant/gaia/tests/jsmarionette/capabilities.json"
npm ERR! You can get their info via:
npm ERR!     npm owner ls gaia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/gaia/npm-debug.log
make: **\* [test-integration-test] Error 1
Connection to 127.0.0.1 closed.

**Comment by zapion** [comment]
@mwargers I'm looking into this issue, seems like a framework error.  after discussing with @shinglyu it's more like import error.  Need more debug message in detail.

**Comment by shinglyu** [comment]
@mwargers: As Paul said, this is more of a GIJ issue. You can try to run `./test/gij_sanity_test.sh`, if it passes, it means the ITP setup OK, the problem lies in the GIJ itself. You might consider submitting the bug to Bugzilla instead.

**Comment by mwargers** [comment]
./test/gij_sanity_test.sh seems to work, at least it says it passes, although Virtualbox stays open afterwards.
I guess this issue can be closed?
