### ISSUE TITLE
scp seems to copy .git files which was not necessary

### ISSUE THREAD

**Issue by zapion** [Mozilla-TWQA/MozITP#9]
might not be a big issue but it appeared in debug log.
Or we can use rsync which provides strong filter function
http://stackoverflow.com/questions/1228466/how-to-filter-files-when-using-scp-to-copy-dir-recursively

**Comment by shinglyu** [comment]
Ya, we should probably ignore the `env-python` folder too. But I don't know if we should use a whitelist or blacklist, and how to make it work smoothly with `vagrant scp`

**Comment by askeing** [comment]
@shinglyu , maybe we can try blacklist, just like `.gitignore`?
